# Generated by Django 4.2.30 on 2026-05-17 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("auth", "Authentication"),
                            ("patient", "Patient"),
                            ("visit", "Visit"),
                            ("billing", "Billing"),
                            ("inventory", "Inventory"),
                            ("staff", "Staff"),
                            ("services", "Services"),
                            ("queue", "Queue"),
                            ("system", "System"),
                            ("discount", "Discount"),
                        ],
                        db_index=True,
                        default="system",
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Short human-readable action label", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Longer detail if needed"),
                ),
                (
                    "object_type",
                    models.CharField(
                        blank=True,
                        help_text='Model name, e.g. "Patient"',
                        max_length=50,
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "object_repr",
                    models.CharField(
                        blank=True,
                        help_text="String representation of the object",
                        max_length=200,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who performed the action (null = system/anonymous)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp", "category"],
                        name="sitemap_act_timesta_1c4e77_idx",
                    ),
                    models.Index(
                        fields=["actor", "-timestamp"],
                        name="sitemap_act_actor_i_42446e_idx",
                    ),
                ],
            },
        ),
    ]
