# Generated by Django 6.0.4 on 2026-04-29 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('payment_confirmed', 'Payment Confirmed'), ('patient_queued', 'Patient Queued'), ('diagnosis_completed', 'Diagnosis Completed'), ('general', 'General')], default='general', max_length=30)),
                ('message', models.TextField()),
                ('target_role', models.CharField(choices=[('all', 'All Staff'), ('receptionist', 'Receptionist'), ('finance', 'Finance'), ('doctor', 'Doctor'), ('admin', 'Admin')], default='all', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffNotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
